package com.fathanpklkt.submissiondicoding;

import android.widget.ArrayAdapter;

import java.util.ArrayList;

public class LangData {
    private static String[] LangName = {
            "Java",
            "C",
            "PHP",
            "SQL",
            "Python",
            "C++",
            "JavaScript",
            "C#",
            "Swift",
            "HTML/CSS"

    };

    private static String[] LangDetail = {
            "Java adalah bahasa pemrograman yang multi platform dan multi device. Sekali anda menuliskan sebuah program dengan menggunakan Java, anda dapat menjalankannya hampir di semua komputer dan perangkat lain yang support Java, dengan sedikit perubahan atau tanpa perubahan sama sekali dalam kodenya. Aplikasi dengan berbasis Java ini dikompulasikan ke dalam p-code dan bisa dijalankan dengan Java Virtual Machine. Fungsionalitas dari Java ini dapat berjalan dengan platform sistem operasi yang berbeda karena sifatnya yang umum dan non-spesifik. Slogan Java adalah Tulis sekali, jalankan di manapun. Sekarang ini Java menjadi sebuah bahasa pemrograman yang populer dan dimanfaatkan secara luas untuk pengembangan perangkat lunak. Kebanyakan perangkat lunak yang menggunakan Java adalah ponsel feature dan ponsel pintar atau smartphone. Setelah membahas mengenai pengertian java, selanjutnya kita membahas mengenai kelebihan dan kekurangan java. Kelebihan Java yang pertama tentu saja multiplatform. Java dapat dijalankan dalam beberapa platform komputer dan sistem operasi yang berbeda. Hal ini sesuai dengan slogannya yangs udah dibahas sebelumnya. Yang kedua adalah OOP atau Object Oriented Programming. Java memiliki library yang lengkap. Library disini adalah sebuah kumpulan dari program yang disertakan dalam Java. Hal ini akan memudahkan pemrograman menjadi lebih mudah. Kelengkapan library semakin beragam jika ditambah dengan karya komunitas Java. Setiap hal pasti memiliki kelebihan dan kekurangan. Kekurangan yang dimiliki oleh Java adalah pada satu slogannya, takni Tulis sekali dan jalankan dimana saja ternyata tidak sepenuhnya benar. Beberapa hal harus disesuaikan jika dijalankan pada platform yang berbeda. Misalnya untuk J2SE dengan platform SWT-AWT bridge tidak dapat berfungsi di Mac OS X. Kekurangan lainnya adalah kemudahan aplikasi Java didekompilasi. Dekompilasi adalah suatu proses membalikkan sebuah aplikasi menjadi kode sumbernya. Hal ini memungkinkan terjadi pada Java karena berupa bytecode yang menyimpan bahasa tingkat tinggi. Hal ini terjadi pula pada platform .NET dari Microsoft sehingga program yang dihasilkan mudah dibajak kodenya karena sulit untuk disembunyikan. Kekurangan Java yang lain adalah penggunaan memori yang cukup banyak, lebih besar daripada bahasa tingkat tinggi sebelum generasi Java. Namun hal ini memang sesuai dengan fitur beragam yang dimiliki oleh Java. Masalah memori ini juga tidak dialami oleh semua pengguna aplikasi Java. Mereka yang sudah menggunakan perangkat keras dengan teknologi terbaru tidak merasakan kelambatan dan konsumsi memori Java yang tinggi. Lain halnya dengan mereka yang menggunakan teknologi lama atau komputer yang sudah berumur tua lebih dari empat tahun akan merasakan adanya kelambatan. Namun apapun kelemahan yang dimiliki Java, faktanya adalah Java merupakan bahasa pemrograman yang populer dan digunakan di seluruh dunia saat ini.",
            "Bahasa pemrograman C merupakan salah satu bahasa pemrograman komputer. Dibuat pada tahun 1972 oleh Dennis Ritchie untuk Sistem Operasi Unix di Bell Telephone Laboratories. Meskipun C dibuat untuk memprogram sistem dan jaringan komputer namun bahasa ini juga sering digunakan dalam mengembangkan software aplikasi. C juga banyak dipakai oleh berbagai jenis platform sistem operasi dan arsitektur komputer, bahkan terdapat beberepa compiler yang sangat populer telah tersedia. C secara luar biasa memengaruhi bahasa populer lainnya, terutama C++ yang merupakan extensi dari C. Pada tahun 1978, Dennis Ritchie dan Brian Kernighan menerbitkan edisi pertama dari buku yang berjudul The C Programming Language. Buku ini hingga sekarang diakui sebagai kitab suci bahasa C dan merupakan referensi utama seorang pemrogram yang ingin mengetahui tentang bahasa C, terutama karena begitu lengkapnya cakupan buku ini tentang bahasa C dan mudahnya program yang dicontohkan dalam buku ini. Versi bahasa C yang ditampilkan dalam buku ini kemudian dikenal dalam kalangan pemrogram sebagai C K&R. Pada buku The C Programming Language edisi kedua kemudian melingkupi ANSI C yang diperkenalkan belakangan. Pada perkembangannya, muncul versi-versi C lain yang pada akhirnya membuat kebingungan di kalangan pemrogram. Karena itu, pada tahun 1983, American National Standards Institute (ANSI) membuat sebuah komite untuk membuat sebuah versi standar dari bahasa C. Setelah melalui proses yang panjang dan sengit, pada tahun 1989, telah berhasil disahkan standar yang dinamakan ANSI X3.159-1989, versi ini seringkali dinamakan ANSI C, atau kadang-kadang C89. Pada 1990, versi ANSI C diadopsi oleh Organization for Standardization (ISO) dengan sedikit perubahan dengan nama ISO/IEC 9899:1990. Versi ini seringkali dinamakan ISO C atau C90. Karena versi ANSI C dan ISO C hanya memiliki sedikit perbedaan, pemanggilan C90 dan C89 merujuk pada bahasa yang sama. Versi C99 dibuat oleh ISO C pada tahun 1999. Versi ini dimaksudkan terutama untuk memperbanyak dukungan kepada pemrograman berorientasi objek, terutama setelah C++, yang dibuat berdasarkan bahasa ini mendapat tempat yang istimewa di kalangan pemrogram yang banyak di cari. Pustaka (seringkali dirujuk sebagai library), adalah kumpulan fungsi-fungsi yang terkandung dalam satu file, Setiap file pustaka mempunyai satu Header file yang menyimpan cetak biru dari fungsi-fungsi yang terkandung dalam file pustaka. Bahasa C seringkali dipakai untuk membuat file-file pustaka yang menyimpan fungsi-fungsi tertentu, dikarenakan C dapat dikompile menjadi bahasa mesin yang sangat cepat dan kecil ukurannya, kemudian bahasa pemrograman lain seperti Python yang akan menciptakan antar-muka dari fungsi-fungsi yang dikandungnya. Pustaka yang paling sering dipakai adalah Pustaka Standar C, yang berisi fungsi-fungsi standar yang berasal dari ANSI C. Pustaka standar ini sekarang telah terkandung dalam hampir setiap kompiler C yang dipakai.",
            "PHP adalah bahasa pemrograman script server-side yang didesain untuk pengembangan web. Selain itu, PHP juga bisa digunakan sebagai bahasa pemrograman umum (wikipedia). PHP di kembangkan pada tahun 1995 oleh Rasmus Lerdorf, dan sekarang dikelola oleh The PHP Group. Situs resmi PHP beralamat di http://www.php.net. PHP disebut bahasa pemrograman server side karena PHP diproses pada komputer server. Hal ini berbeda dibandingkan dengan bahasa pemrograman client-side seperti JavaScript yang diproses pada web browser (client). Pada awalnya PHP merupakan singkatan dari Personal Home Page. Sesuai dengan namanya, PHP digunakan untuk membuat website pribadi. Dalam beberapa tahun perkembangannya, PHP menjelma menjadi bahasa pemrograman web yang powerful dan tidak hanya digunakan untuk membuat halaman web sederhana, tetapi juga website populer yang digunakan oleh jutaan orang seperti wikipedia, wordpress, joomla, dll. Saat ini PHP adalah singkatan dari PHP: Hypertext Preprocessor, sebuah kepanjangan rekursif, yakni permainan kata dimana kepanjangannya terdiri dari singkatan itu sendiri: PHP: Hypertext Preprocessor. PHP dapat digunakan dengan gratis (free) dan bersifat Open Source. PHP dirilis dalam lisensi PHP License, sedikit berbeda dengan lisensi GNU General Public License (GPL) yang biasa digunakan untuk proyek Open Source. Kemudahan dan kepopuleran PHP sudah menjadi standar bagi programmer web di seluruh dunia. Menurut wikipedia pada februari 2014, sekitar 82% dari web server di dunia menggunakan PHP. PHP juga menjadi dasar dari aplikasi CMS (Content Management System) populer seperti Joomla, Drupal, dan WordPress. Untuk membuat halaman web, sebenarnya PHP bukanlah bahasa pemrograman yang wajib digunakan. Kita bisa saja membuat website hanya menggunakan HTML saja. Web yang dihasilkan dengan HTML (dan CSS) ini dikenal dengan website statis, dimana konten dan halaman web bersifat tetap. Sebagai perbandingan, website dinamis yang bisa dibuat menggunakan PHP adalah situs web yang bisa menyesuaikan tampilan konten tergantung situasi. Website dinamis juga bisa menyimpan data ke dalam database, membuat halaman yang berubah-ubah sesuai input dari user, memproses form, dll. Untuk pembuatan web, kode PHP biasanya di sisipkan ke dalam dokumen HTML. Karena fitur inilah PHP disebut juga sebagai Scripting Language atau bahasa pemrograman script.",
            "SQL adalah Structured Query Language yaitu suatu bahasa khusus yang digunakan untuk membuat dan mengolah database. Bagi anak IT tentu sangat penting untuk belajar dan mengenal SQL, karena anda akan bersinggungan terus dengan SQL saat mulai belajar dan mengolah database. Oleh karena itu disini akan kita kupas tuntas tentang SQL. Structured Query Language atau biasa disebut SQL adalah suatu bahasa khusus yang digunakan untuk mengakses data-data yang ada di dalam sebuah database relasional. SQL adalah bahasa komputer yang menggunakan standar ANSI (American Nasional Standard Institute) yang dipakai dalam manajemen database relasional. Dengan SQL atau bisa juga disebut query kita dapat memanipulasi atau mengedit database sesuai yang kita kehendaki. seperti menjalankan query untuk mengambil data, menambah data, memperbarui data dan menghapus data. Sampai sekarang hampir keseluruhan server database maupun software – software database lainnya mengenal serta mampu mengartikan bahasa SQL. oleh karenanya belajar bahasa SQL sangat penting bagi yang bergelut dibidang IT maupun yang selalu bersinggungan dengan database relasional. Artikel dari Jhonny Oracle seorang peniliti dari IBM yang memulai sejarah SQL, dalam artikelnya Jhonny membahas tentang ide membuat basis data. Artikel tersebut dibuat pada bulan Juni 1970. inilah yang mengawali lahirnya SQL. Selain itu dalam artikel juga membahas kemungkinan penggunaan bahasa standar guna mengakses data yang terdapat dalam basis data tersebut. bahasa tersebut diberi nama SEQUEL (Structured English Query Language). Setelah artikel dirilis, IBM mulai menjalankan proyek pembuatan basis data relasional dengan menggunakan bahasa SEQUEL. Namun akhirnya penamaan SEQUEL dirubah oleh IBM menjadi SQL, hal ini didasari karena adanya permasalahan hukum mengenai penamaan SEQUEL. Implementasi dari basis data relasional dikenal dengan sebutan System/R. Akhir tahun 1970-an, lahirlah perusahaan Oracle yang menciptakan server basis data populer yang diberi nama Oracle, sama dengan nama perusahaan tersebut. Tingkat kepopuleran Jhonny Oracle  semakin meningkat hal ini juga berimbas kepada tingkat kepopuleran SQL sampai saat ini, sehingga SQL menjadi standar bahasa dalam manajemen basis data. Pada tahun 1986 dilakukan standarisasi untuk bahasa SQL, hai ini ditandai dengan dikeluarkannya standar SQL oleh ANSI, standarisasi ini biasa disebut SQL86. Pada tahun 1989, standar SQL mengalami perbaikan dan kemudian diperbaiki lagi pada tahun 1992. Versi terakhir ini dikenal dengan sebutan SQL92. Sebenarnya pada tahun 1999 dikeluarkan standar baru yaitu SQL99 namun kebanyakan implementasi mereferensi pada SQL92.",
            "Python merupakan bahasa pemrograman yang populer dan banyak digunakan oleh Data Analysts, Data Scientists dan para Software Engineers untuk menjalankan proses pembangunan sebuah aplikasi dan untuk menggali lebih dalam machine learning. Perusahaan seperti google, spaceX dan Instagram membutuhkannya untuk membersihkan data, membangun prediksi, model untuk AI, web app, dan masih banyak lagi. Berikut adalah beberapa hal yang dibangun dari Python dan sudah kamu rasakan dalam kehidupan sehari-hari: Artificial Intelligence (AI) atau yang biasa disebut dengan kecerdasan buatan ini merupakan tombak utama dari AI. Contohnya adalah saat pebisnis membutuhkan chat otomatis untuk menjawab pertanyaan dari para costumer-nya. Untuk hal ini programmer dapat menggunakan Python untuk mengidentifikasi email yang masuk beserta jawabannya dan kemudian memvisualkan jawaban yang diinginkan oleh pebisnis dan merancang prediksi jawaban yang diinginkan. Python juga dapat digunakan untuk memprediksi model jawaban melalui aplikasi chatbot untuk respons yang lebih cepat tanggap. Aplikasi Web Python merupakan bagian penting dari beberapa website yang paling banyak dikunjungi abad ini seperti Pinterest, Instagram, Spotify, dan Youtube. Faktanya Pinterest sudah menggunakan Python dari awal web ini dibangun. Itulah mengapa bookmarking oleh halaman web ini begitu terstruktur dan mudah untuk diatur. Special Effect pada Hollywood Ingatkah kamu adegan ledakan dalam film action? Ada banyak perusahaan yang bergerak di bidang perfilman seperti Lucasfilm yang menggunakan Python sebagai sebagai special effect. Dengan menggunakan Python perusahaan perfilman dapat menghemat banyak waktu dalam membuat effect. Menggunakan Python dalam memprediksikan kemungkinan-kemungkinan yang terjadi di suatu bisnis sangat diperlukan untuk zaman ini. Apakah kamu siap mempelajari bahasa pemrograman Python lebih dalam?  ",
            "Bahasa C++ diciptakan oleh Bjarne Stroustrup di AT&T Bell Laboratories awal tahun 1980-an berdasarkan C ANSI (American National Standard Institute). Pertama kali, prototype C++ muncul sebagai C yang dipercanggih dengan fasilitas kelas. Bahasa tersebut disebut C dengan kelas ( C wih class). Selama tahun 1983-1984, C dengan kelas disempurnakan dengan menambahkan fasilitas pembeban lebihan operator dan fungsi yang kemudian melahirkan apa yang disebut C++. Symbol ++ merupakan operator C untuk operasi penaikan, muncul untuk menunjukkan bahwa bahasa baru ini merupakan versi yang lebih canggih dari C. Borland International merilis compiler Borland C++ dan Turbo C++. Kedua compiler ini sama-sama dapat digunakan untuk mengkompilasi kode C++. Bedanya, Borland C++ selain dapat digunakan dibawah lingkungan DOS, juga dapat digunakan untuk pemrograman Windows. C++ merupakan bahasa pemrograman yang memiliki sifat Pemrograman berorientasi objek, Untuk menyelesaikan masalah, C++ melakukan langkah pertama dengan menjelaskan class-class yang merupakan anak class yang dibuat sebelumnya sebagai abstraksi dari object-object fisik, Class tersebut berisi keadaan object, anggota-anggotanya dan kemampuan dari objectnya, Setelah beberapa Class dibuat kemudian masalah dipecahkan dengan Class. Bahasa C adalah bahasa pemrograman prosedural yang memungkinkan kita untuk membuat prosedur dalam menyelesaikan suatu masalah. Bahasa pemrograman C++ adalah bahasa pemrograman yang berorientasi pada objek. Perbedaan Antara Bahasa pemrograman C dan C++ meskipun bahasa-bahasa tersebut menggunakan sintaks yang sama tetapi mereka memiliki perbedaan, C merupakan bahasa pemrograman prosedural, dimana penyelesaian suatu masalah dilakukan dengan membagi-bagi masalah tersebut kedalam su-submasalah yang lebih kecil, sedangkan untuk C++ merupakan bahasa pemrograman yang memiliki sifat Pemrograman berorientasi objek, Untuk menyelesaikan masalah, C++ melakukan langkah pertama dengan menjelaskan class-class yang merupakan anak class yang dibuat sebelumnya sebagai abstraksi dari object-object fisik, Class tersebut berisi keadaan object, anggota-anggotanya dan kemampuan dari objectnya, Setelah beberapa Class dibuat kemudian masalah dipecahkan dengan Class. Di dalam bahasa pemrograman C++ terdapat Pengarah Preprocessor Dalam Bahasa Pemrograman  C atau C++ bagian pertama yang menyusun sebuah tugas, terbentuk di pengarah preprocessor. Pengarah preprocessor menginstruksikan compiler untuk membentuk beberapa tugas sebelum komplisasi dimulai. Pengarah preprocessor #include ,salah satu yang sering terlihat,contoh #include<stdio.h> menginstruksikan compiler untuk menyertakan berkas C++ sumber yang lain sebelum kompilasi dimulai. Pengarah preprocessor yang lain adalah #define, yang merupakan definisi sebuah macro.",
            "JavaScript adalah bahasa skrip yang populer di internet dan dapat bekerja di sebagian besar penjelajah web populer seperti Internet Explorer (IE), Mozilla Firefox, Netscape dan Opera. Kode JavaScript dapat disisipkan dalam halaman web menggunakan tag SCRIPT. javascript berfungsi membuat sebuah halaman website lebih interaktif dan dinamis. Penggunaan kode javascript sangat dibutuhkan untuk website-website yang berorientasi pada kenyamanan pengakses (user-experience). Namun, penggunaan kode javascript ini tidak akan maksimal jika tidak dibarengi dengan penggunaan css karena javascript juga tidak akan lepas dari html. Ketiga bahasa pemrograman itu sangat erat kaitannya. Jika saya ibaratkan sebuah website adalah rumah, maka kode html adalah segala yang membangun dan ada dirumah tersebut (tembok, tiang, atap, pondasi, ruang keluarga, kamar, dapur, peralatan rumah tangga, dan sebagainya). Lalu, kode css adalah pengatur dan penghias rumah tersebut(tata letak, warna dan sebagainya). Dan peran javascript bisa sebagai ‘pembantu’ kode css agar pengaturan dan hiasannya lebih bagus dengan tambahan pernak-pernik misalnya. Bisa juga untuk memanipulasi kode html dengan nama/identitas tertentu. Manipulasi ini bisa berupa menyembunyikan, menganti bahkan menambahkan elemen html yang baru. Tanpa javascript, saat melakukan aksi tertentu, misalnya meng-klik pada sebuah halaman website, maka hasil atau respon dari hasil klik tersebut harus dimuat pada halaman lain. Hal ini tentunya sangat merepotkan karena tidak setiap aksi klik menghasilkan hasil/output yang besar/banyak. Terkadang hasil sebuah aksi hanyalah sebuah kalimat “Anda berhasil memasukkan data” Hampir semua website saat ini menggunakan javascript, tapi ketahuilah bahwa pengakses website bisa mematikan fitur javascript pada browsernya, sehingga website yang diakses akan tampil sebagaimana tampil tanpa javascript. Hal ini bisa membuat tampilan website anda acak-acakan jika anda terlalu bergantung pada kode javascript untuk mendesainnya.",
            "C# atau yang dibaca C sharp adalah bahasa pemrograman sederhana yang digunakan untuk tujuan umum, dalam artian bahasa pemrograman ini dapat digunakan untuk berbagai fungsi misalnya untuk pemrograman server-side pada website, membangun aplikasi desktop ataupun mobile, pemrograman game dan sebagainya. Selain itu C# juga bahasa pemrograman yang berorientasi objek, jadi C# juga mengusung konsep objek seperti inheritance, class, polymorphism dan encapsulation. Dalam prakteknya C# sangat bergantung dengan framework yang disebut .NET Framework, framework inilah yang nanti digunakan untuk mengcompile dan menjalankan kode C#. C# dikembangkan oleh Microsoft dengan merekrut Anders Helsberg. Tujuan dibangunnya C# adalah sebagai bahasa pemrograman utama dalam lingkungan .NET Framework (lihat C#). Banyak pihak juga yang menganggap bahwa Java dengan C# saling bersaing, bahkan ada juga yang menyatakan jika pernah belajar Java maka belajar C# akan sangat mudah dan begitu juga sebaliknya. Anggapan tersebut sebenarnya tidak salah karena perlu diketahui sebelum adanya C# Microsoft mengembangkan J++ dengan maksud mencoba membuat Java agar berjalan pada platform Windows, karena adanya masalah dari pihak luar maka Microsoft menghentikan proyek J++ dan beralih untuk mengembangkan bahasa baru yaitu C#. Dalam mengembangkan aplikasi ataupun fungsi-fungsi lain yang berbasis C#, kita perlu IDE (Integrated Development Environment) untuk membantu pekerjaan kita. Di Windows kita dapat menggunakan Visual Studio yang memiliki fitur yang sangat lengkap. Akan tetapi tidak semua dari kita memakai OS (Operating System) Windows dan memiliki kapasitas harddisk yang memadai karena perlu diketahui Visual Studio ini sangat memakan tempat di harddisk kita. Karena itu ada IDE alternatif Visual Studio yaitu Xamarin Studio yang bisa dipakai lintas platform yang fiturnya menurut saya tidak kalah hebatnya dengan Visual Studio dan lebih dari cukup untuk membangun aplikasi C#. Selain itu ada juga tool seperti SharpDevelop namun sepertinya hanya bisa untuk platform Windows. Oh iya bagi pembaca yang memakai OS selain windows dapat memakai Mono untuk pengganti .NET Framework. Sebenarnya penulis sendiri lebih suka menggunakan Sharp Develop karena mengingat spesifikasi laptop yang memiliki processor Atom dan dipersenjatai harddisk sebesar 18 GB, selain itu juga Sharp Develop juga mudah digunakan oleh pemula seperti saya. Jadi kesimpulannya untuk platform Windows kamu bisa memilih dari ketiga itu atau mau semuanya juga terserah, akan tetapi untuk OS Mac OS X dan Linux kamu hanya dapat memakai Xamarin Studio.",
            "Swift adalah bahasa pemrograman yang diciptakan oleh Chris Lattner di bawah naungan perusahaan Apple Inc., Amerika Serikat. Swift versi 1.0 diluncurkan resmi pada pertengahan tahun 2014. Di akhir tahun 2015, bersamaan dengan versi 2.2, Apple melepas Swift menjadi sebuah proyek kode terbuka di swift.org. Saat artikel ini ditulis di akhir tahun 2016, Swift telah berada di versi 3.0. Bahasa pemrograman Swift adalah bahasa multiguna (general purpose) yang artinya Swift bisa digunakan untuk membuat program apa saja, baik itu aplikasi desktop, aplikasi server, aplikasi mobile, dan lain sebagainya. Swift berpegang pada 3 prinsip utama, yaitu: mudah, cepat, dan aman. Mudah maksudnya kode program Swift mudah ditulis, mudah dibaca, dan mudah dipahami. Cepat maksudnya kode program Swift bekerja dengan cepat dan memiliki kinerja yang bagus. Aman maksudnya kode program Swift mencegah penulisan program yang akan mengakibatkan kesalahan, baik yang disengaja maupun tidak, dari pembuat program. Swift membiasakan pemrogram untuk menulis kode program secara baik dan benar. Swift dari Apple membuat aplikasi jadi (executable) dengan metode kompilasi (compiled), bukan diterjemahkan (interpreted) maupun dikelola (managed). Metode kompilasi menghasilkan aplikasi asli (native) yang berjalan langsung pada mesin dan sistem operasi tempat aplikasi dijalankan, tanpa bantuan aplikasi tambahan penerjemah (interpreter) atau pun VM (virtual machine). Dalam hal ini, Swift seperti bahasa C/C++ atau Free Pascal, bukan seperti Python atau PHP (yang membutuhkan interpreter), tidak juga seperti JavaScript, Java, atau C# (yang membutuhkan runtime atau VM). Hal ini merupakan salah satu faktor yang membuat aplikasi Swift berkinerja baik dan cepat. Kompilator (compiler) Swift memanfaatkan perangkat lunak LLVM yang juga merupakan proyek kode terbuka. Sebagai bahasa pemrograman baru yang modern, Swift mengadopsi banyak sekali hal baik dari bahasa pemrograman lainnya, namun juga berusaha menghindari banyak hal buruk dari bahasa pemrograman lainnya. Jadi jangan heran jika dalam beberapa aspek Swift tampak seperti bahasa lain, sekaligus juga tampak baru dalam beberapa aspek lainnya. Swift mendukung berbagai paradigma pemrograman, baik itu procedural, object-oriented, maupun functional. Namun yang menjadi unggulan Swift sendiri adalah pemrograman berorientasi protokol (protocol oriented programming atau POP). Apa itu POP? Nanti kita bahas pada bab selanjutnya. Swift dibuat di bawah naungan perusahaan Apple. Dan sejak v.2.0, Swift telah dinyatakan sebagai bahasa pemrograman resmi di lingkungan produk Apple, yang secara bertahap akan menggantikan bahasa resmi sebelumnya yaitu Objective-C. Dengan demikian, belajar Swift yang paling nyaman adalah dengan menggunakan perangkat Apple, baik itu perangkat keras maupun perangkat lunaknya.",
            "Berbicara soal HTML tidak hanya terbatas pada pengertiannya saja. Anda harus tahu seluk-beluknya jika ingin mahir bahasa markup yang satu ini. HTML adalah singkatan dari Hypertext Markup Language. HTML memungkinkan seorang user untuk membuat dan menyusun bagian paragraf, heading, link atau tautan, dan blockquote untuk halaman web dan aplikasi. HTML bukanlah bahasa pemrograman, dan itu berarti HTML tidak punya kemampuan untuk membuat fungsionalitas yang dinamis. Sebagai gantinya, HTML memungkinkan user untuk mengorganisir dan memformat dokumen, sama seperti Microsoft Word. Ketika bekerja dengan HTML, kami menggunakan struktur kode yang sederhana (tag dan attribute) untuk mark up halaman website. Misalnya, kami membuat sebuah paragraf dengan menempatkan enclosed text di antara tag pembuka <p>  dan tag penutup </p>. HTML dibuat oleh Tim Berners-Lee, seorang ahli fisika di lembaga penelitian CERN yang berlokasi di Swiss. Dia memiliki ide tentang sistem hypertext yang berbasis internet. Hypertext merujuk pada teks yang memuat referensi (link) ke teks lain yang bisa diakses langsung oleh viewer. Tim merilis versi pertama HTML pada tahun 1991, dan di dalamnya terdiri atas 18 HTML tag. Sejak saat itu, setiap kali bahasa HTML merilis versi teranyarnya, selalu ada tag dan attribute (tag modifier) terbaru. Berdasarkan HTML Element Reference milik Mozilla Developer Network, untuk saat ini, ada 140 HTL tag meskipun sebagiannya sudah usang (tidak lagi didukung oleh versi terbaru browser). Berkat popularitasnya yang terus meningkat, HTML kini dianggap sebagai web standard yang resmi. Spesifikasi HTML di-maintain dan dikembangkan oleh World Wide Web Consortiumm (W3C). Cek versi terbaru dari bahasa ini di website W3C. Upgrade HTML besar-besaran terjadi pada tahun 2014, dan hasilnya adalah pengenalan HTML5. Pada upgrade tersebut, terdapat semantic baru yang memberitahukan arti dari kontennya sendiri, seperti <artcile>, <header>, dan <footer>. "
    };

    private static int[] LangImage = {
            R.drawable.java_logo,
            R.drawable.c_logo,
            R.drawable.php_logo,
            R.drawable.sql_logo,
            R.drawable.python_logo,
            R.drawable.cp_logo,
            R.drawable.js_logo,
            R.drawable.csh_logo,
            R.drawable.swift_logo,
            R.drawable.html_logo
    };


    static ArrayList<Lang> getListData() {
        ArrayList<Lang> list = new ArrayList<>();
        for (int position = 0; position < LangName.length; position++) {
            Lang hero = new Lang();
            hero.setName(LangName[position]);
            hero.setDetail(LangDetail[position]);
            hero.setPhoto(LangImage[position]);
            list.add(hero);
        }
        return list;
    }
}
